services:
  go_app:
    build:
      context: ./
      dockerfile: DOCKERFILE
    container_name: go_app
    ports: 
      - 80:80
    depends_on:
      - go_db
  
  go_db:
    image: mysql
    container_name: go_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: go_db 
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - go_db_data:/var/lib/mysql
    networks:
      - net

volumes:
  go_db_data:

networks:
  net:
    driver: bridge
