version: '3.1'
services:

  app:
    build:
      context: ./
      dockerfile: php.dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - 80:80 
    volumes:
      - ../ROOT_DIR:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/custom.conf:/etc/apache2/sites-available/custom.conf
    networks:
      - net

  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database_name
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - app_data:/var/lib/mysql
    networks:
      - net

volumes:
  app_data:

networks:
  net:
    driver: bridge